# Generated by Django 4.2.16 on 2024-10-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("vaccination", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="accounts.parent",
            ),
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccination_records",
                to="vaccination.child",
            ),
        ),
    ]
